# clash.yaml https://github.com/anaer/Sub/blob/main/clash.yaml
aria2c -d . --check-certificate=false --max-connection-per-server=5 --max-concurrent-downloads=10 --split=100 --min-split-size=1M --continue=true --optimize-concurrent-downloads=true --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://ghproxy.net/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://raw.fastgit.org/anaer/Sub/main/clash.yaml https://slink.ltd/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://gh.con.sh/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://git.xfj0.cn/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://hub.gitmirror.com/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://jsdelivr.b-cdn.net/gh/anaer/Sub@main/clash.yaml https://gcore.jsdelivr.net/gh/anaer/Sub@main/clash.yaml https://cdn.jsdelivr.net/gh/anaer/Sub@main/clash.yaml https://jsd.onmicrosoft.cn/gh/anaer/Sub@main/clash.yaml https://jsd.cdn.zzko.cn/gh/anaer/Sub@main/clash.yaml https://cdn.statically.io/gh//anaer/Sub/main/clash.yaml https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml

# geoip.dat https://github.com/MetaCubeX/meta-rules-dat/blob/release/geoip.dat
aria2c -d . --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://gh.con.sh/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://ghps.cc/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://git.xfj0.cn/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://hub.gitmirror.com/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://raw.fastgit.org/MetaCubeX/meta-rules-dat/release/geoip.dat https://ghproxy.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://jsdelivr.b-cdn.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat

# geosite.dat https://github.com/MetaCubeX/meta-rules-dat/blob/release/geosite.dat
aria2c -d . --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://gh.con.sh/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://ghps.cc/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://git.xfj0.cn/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://hub.gitmirror.com/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://raw.fastgit.org/MetaCubeX/meta-rules-dat/release/geosite.dat https://ghproxy.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://jsdelivr.b-cdn.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat

# Country.mmdb https://github.com/alecthw/mmdb_china_ip_list/blob/release/Country.mmdb
aria2c -d . --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://gh.con.sh/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://ghps.cc/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://git.xfj0.cn/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://github.moeyy.xyz/https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://hub.gitmirror.com/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://raw.fastgit.org/alecthw/mmdb_china_ip_list/release/Country.mmdb https://ghproxy.net/https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://jsdelivr.b-cdn.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb https://gcore.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb

# mihomo-darwin-amd64.gz https://github.com/anaer/mihomo/releases        
# aria2c -d . --check-certificate=false --max-connection-per-server=5 --max-concurrent-downloads=10 --split=100 --min-split-size=1M --continue=true --optimize-concurrent-downloads=true --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://git.814560.xyz/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://dl.ghpig.top/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://ghproxy.liuzhicong.com/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://gh.ddlc.top/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://slink.ltd/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://git.xfj0.cn/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://gh.con.sh/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://hub.gitmirror.com/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://download.fastgit.org/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://kkgithub.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://521github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz https://githubfast.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-darwin-amd64.gz