@REM clash.yaml https://github.com/anaer/Sub/blob/main/clash.yaml
aria2c --check-certificate=false --max-connection-per-server=5 --max-concurrent-downloads=10 --split=100 --min-split-size=1M --continue=true --optimize-concurrent-downloads=true --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://ghproxy.net/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://raw.fastgit.org/anaer/Sub/main/clash.yaml https://slink.ltd/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://gh.con.sh/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://git.xfj0.cn/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://hub.gitmirror.com/https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml https://jsdelivr.b-cdn.net/gh/anaer/Sub@main/clash.yaml https://gcore.jsdelivr.net/gh/anaer/Sub@main/clash.yaml https://cdn.jsdelivr.net/gh/anaer/Sub@main/clash.yaml https://jsd.onmicrosoft.cn/gh/anaer/Sub@main/clash.yaml https://jsd.cdn.zzko.cn/gh/anaer/Sub@main/clash.yaml https://cdn.statically.io/gh//anaer/Sub/main/clash.yaml https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml

@REM geoip.dat https://github.com/MetaCubeX/meta-rules-dat/blob/release/geoip.dat
aria2c --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://gh.con.sh/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://ghps.cc/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://git.xfj0.cn/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://hub.gitmirror.com/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://raw.fastgit.org/MetaCubeX/meta-rules-dat/release/geoip.dat https://ghproxy.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat https://jsdelivr.b-cdn.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geoip.dat

@REM geosite.dat https://github.com/MetaCubeX/meta-rules-dat/blob/release/geosite.dat
@REM aria2c --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://gh.con.sh/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://ghps.cc/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://git.xfj0.cn/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://github.moeyy.xyz/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://hub.gitmirror.com/https://raw.github.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://raw.fastgit.org/MetaCubeX/meta-rules-dat/release/geosite.dat https://ghproxy.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat https://jsdelivr.b-cdn.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat https://gcore.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/release/geosite.dat

@REM Country.mmdb https://github.com/alecthw/mmdb_china_ip_list/blob/release/Country.mmdb
aria2c --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://slink.ltd/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://gh.con.sh/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://ghps.cc/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://git.xfj0.cn/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://github.moeyy.xyz/https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://hub.gitmirror.com/https://raw.github.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://raw.fastgit.org/alecthw/mmdb_china_ip_list/release/Country.mmdb https://ghproxy.net/https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb https://jsdelivr.b-cdn.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb https://gcore.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb

@REM mihomo-windows-amd64.zip https://github.com/anaer/mihomo/releases        
aria2c --check-certificate=false --max-connection-per-server=5 --max-concurrent-downloads=10 --split=100 --min-split-size=1M --continue=true --optimize-concurrent-downloads=true --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://git.814560.xyz/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://dl.ghpig.top/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://ghproxy.liuzhicong.com/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://gh.ddlc.top/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://slink.ltd/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://git.xfj0.cn/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://gh.con.sh/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://download.fgit.cf/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://hub.gitmirror.com/https://github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://download.fastgit.org/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://kkgithub.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://521github.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip https://githubfast.com/anaer/mihomo/releases/download/Prerelease-Alpha/mihomo-windows-amd64.zip

@REM mihomo-windows-amd64-v1.18.0.zip https://github.com/MetaCubeX/mihomo/releases
@REM aria2c --check-certificate=false -x 15 -j 10 -s 100 -c --connect-timeout=10 --timeout=10 --lowest-speed-limit=1K --allow-overwrite=true  https://git.814560.xyz/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://dl.ghpig.top/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://mirror.ghproxy.com/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://ghproxy.liuzhicong.com/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://cwb0207.online/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://999740.xyz/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://download.fastgit.org/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://gh.ddlc.top/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://slink.ltd/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://git.xfj0.cn/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://gh.con.sh/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://ghps.cc/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://download.fgit.cf/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip https://hub.gitmirror.com/https://github.com/MetaCubeX/mihomo/releases/download/v1.18.0/mihomo-windows-amd64-v1.18.0.zip

ping 127.0.0.1 -n 3 > nul

@pause